version: '{build}'
os: Visual Studio 2015
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    dnvm install 1.0.0-beta8
build_script:
- ps: .\package.ps1
artifacts:
- path: artifacts/packages/*.nupkg
